send date when the question was dropped
openstax/tutor-server pull request #2207
Opened 2020-10-02 16:04 UTC by camliu89

2020-10-05 16:49 UTC, Dantemss requested changes

2020-10-05 16:49 UTC, Dantemss commented on app/representers/api/v1/task_plan/dropped_question_representer.rb
> +           writeable: true,
Writeable should be false

2020-10-05 16:49 UTC, Dantemss commented on app/representers/api/v1/task_plan/dropped_question_representer.rb
> +           schema_info: { required: true }
I would say leave this out

2020-10-05 16:49 UTC, Dantemss commented
Pushed change to hopefully fix graded question count when dropping questions.

2020-10-09 16:26 UTC, nathanstitt approved these changes

2020-10-09 17:26 UTC, merged