WIP remap teacher exercises and practice questions
openstax/tutor-server pull request #2245
Opened 2020-12-18 01:42 UTC by jivey

2020-12-18 20:05 UTC, jivey commented
@nathanstitt @Dantemss I still need to write a spec for that UpdateTaskPlanEcosystem change, but I'd appreciate some 👀 on this in case changes are needed.

2020-12-21 19:04 UTC, jivey commented on app/routines/update_task_plan_ecosystem.rb
> +      outputs.task_plan.settings['page_ids'].uniq!
Something I'm wondering about this addition, did new ecosystem page ids not get picked up before?

2020-12-22 17:11 UTC, nathanstitt approved these changes

2020-12-22 17:11 UTC, nathanstitt commented on app/routines/update_task_plan_ecosystem.rb
> -    return if old_ecosystem == ecosystem
I'm curious why this was removed.  it seems like if the ecosystems match there's nothing to do and we can quit early

2020-12-22 17:11 UTC, nathanstitt commented on app/routines/update_task_plan_ecosystem.rb
> +      outputs.task_plan.settings['page_ids'].uniq!
there's probably pages that have no exercises?

2020-12-22 17:13 UTC, jivey commented on app/routines/update_task_plan_ecosystem.rb
> -    return if old_ecosystem == ecosystem
The docs wanted a cloned task plan to always grab the latest exercise even if the ecosystem is the same.

2020-12-22 17:14 UTC, nathanstitt commented on app/routines/update_task_plan_ecosystem.rb
> -    return if old_ecosystem == ecosystem
ah that makes sense

2020-12-22 17:26 UTC, Dantemss requested changes
Main thing is we can't mutate existing Content::Exercises

2020-12-22 17:26 UTC, Dantemss commented on app/routines/update_task_plan_ecosystem.rb
> +      outputs.task_plan.settings['page_ids'].uniq!
The page_ids get set on line 52.

2020-12-22 17:26 UTC, Dantemss commented on app/subsystems/content/routines/remap_teacher_exercises.rb
> +      exercises.update_all(content_page_id: to) if save
We can't really update the existing ones or existing assignments will be inconsistent. We'd have to make copies.

2020-12-22 17:26 UTC, Dantemss commented on app/routines/update_task_plan_ecosystem.rb
> -    return if old_ecosystem == ecosystem
I think because of version updates.

2020-12-22 17:26 UTC, Dantemss commented on app/subsystems/content/import_book.rb
> +    run(:remap_teacher_exercises, ecosystem: ecosystem, save: true)
This runs before we assign the new book to the courses, another reason why we can't modify existing exercises here.

2020-12-22 17:26 UTC, Dantemss commented on app/subsystems/content/routines/remap_practice_question_exercises.rb
> +    end
This can be up to 10000 queries which is pretty slow. Fine for now but let's fix for Fall 2021.

2020-12-22 19:05 UTC, Dantemss approved these changes
Looks good

2020-12-22 19:07 UTC, merged