WIP: add assignment-type tag to replace old "type" tag
openstax/tutor-server pull request #2260
Opened 2021-01-19 22:58 UTC by nathanstitt

Still a lot to do but put on hold until https://github.com/openstax/tutor-server/pull/2208 is complete

2021-02-08 16:30 UTC, Dantemss requested changes
Some of the logic needs changes

2021-02-08 16:30 UTC, Dantemss commented on app/subsystems/content/routines/populate_exercise_pools.rb
> +            tags.include?('assignment-type:homework')
This should be just `assignment-type:reading`, not homework.

2021-02-08 16:30 UTC, Dantemss commented on app/subsystems/content/routines/populate_exercise_pools.rb
> +          if tags.include?('assignment-type:practice')
This should be `assignment-type:homework`, practice doesn't exist.

2021-02-08 16:30 UTC, Dantemss commented on app/subsystems/content/routines/populate_exercise_pools.rb
> +          if tags.include?('assignment-type:practice')
This should be `assignment-type:homework`.

2021-02-09 00:15 UTC, nathanstitt commented on lib/openstax/exercises/v1/real_client.rb
@jivey @Dantemss I FINALLY tracked this down as the cause of why exercises would reply without the correctness or feedback.  We weren't supplying a token, causing it to be an anon request.

I think this is safe to do so since we're filtering out the Authorization header in the vcr config, but curious what you guys think?  There's a brand new cassette in this PR that we can check

2021-02-09 00:16 UTC, nathanstitt commented on spec/routines/populate_preview_course_content_spec.rb
> +    ecosystem = generate_mini_ecosystem
the `generate_mini_ecosystem` helper will import 2 pages (4.1, 4.2) from college physics as a "book". It has the pages and exercises stored in a cassette.

2021-02-09 16:00 UTC, jivey commented on lib/openstax/exercises/v1/real_client.rb
@nathanstitt I thought I'd mentioned this awhile back, sorry! Yes, this was the cause of the issue I had. I didn't commit it because it stored correctness in the cassette. I had thought to use the VCR filter hooks to randomly change the correctness before it records, but didn't get far in exploring that.

2021-02-09 16:02 UTC, jivey commented on spec/routines/populate_preview_course_content_spec.rb
> +    ecosystem = generate_mini_ecosystem
I love this!

2021-02-12 19:48 UTC, Dantemss reviewed
Looks great, just have a few comments/questions

2021-02-12 19:48 UTC, Dantemss commented on spec/lib/openstax/cnx/v1/fragment_splitter_spec.rb
> +        #                                  OpenStax::Cnx::V1::Fragment::Video,
This was the only test for splitting into a Video, not sure if it matters.

2021-02-12 19:48 UTC, Dantemss commented on spec/subsystems/content/routines/transform_and_cache_page_content_spec.rb
> +  # end
Is this no longer relevant?

2021-02-12 19:48 UTC, Dantemss commented on spec/subsystems/tasks/populate_placeholder_steps_spec.rb
> +        # )
I'm guessing you can re-add this once the other issues with this spec are fixed.

2021-02-12 19:50 UTC, nathanstitt commented on spec/lib/openstax/cnx/v1/fragment_splitter_spec.rb
> +        #                                  OpenStax::Cnx::V1::Fragment::Video,
yah I think I'd commented this out inadvertently and meant to re-enable it. I'll do so

2021-02-12 19:51 UTC, nathanstitt commented on spec/subsystems/content/routines/transform_and_cache_page_content_spec.rb
> +  # end
same as above, I think it should be re-enabled

2021-02-12 19:55 UTC, Dantemss commented on spec/subsystems/content/routines/transform_and_cache_page_content_spec.rb
> +  # end
Actually this spec has a massive cassette still in the repo... I might be fine deleting it if we get rid of that...

2021-02-12 19:56 UTC, Dantemss commented
Maybe spec/cassettes/Content_ImportBook/with_the_bio_book.yml and spec/cassettes/sets_the_exercise_s_context_from_the_Section_Summary.yml can be deleted?

2021-02-15 20:05 UTC, nathanstitt commented on spec/lib/openstax/cnx/v1/fragment_splitter_spec.rb
> +        #                                  OpenStax::Cnx::V1::Fragment::Video,
I got this working now, thanks for pointing it out

2021-02-15 20:07 UTC, nathanstitt commented on spec/subsystems/content/routines/transform_and_cache_page_content_spec.rb
> +  # end
sounds good to me

2021-02-15 20:07 UTC, nathanstitt commented on spec/subsystems/tasks/populate_placeholder_steps_spec.rb
> +        # )
yep, did so

2021-02-15 20:09 UTC, nathanstitt commented
@Dantemss I did comment out a few specs that failed under CI but passed locally.  I marked them with a TODO so we can grep for them later

2021-02-22 17:26 UTC, merged