add offerings to bootstrap data
openstax/tutor-server pull request #2268
Opened 2021-02-23 16:42 UTC by jivey

We decided to include this in the bootstrap data as it's needed most of the time anyway.

2021-02-23 16:47 UTC, nathanstitt commented on app/representers/api/v1/bootstrap_data_representer.rb
>  end
while they're not really sensitive, we should only send the offerings to teachers. No read to send to students.  You can use `user_options` to the representer to indicate if they should be included.  https://github.com/openstax/tutor-server/blob/main/app/representers/api/v1/exercise_representer.rb#L37-L40 has an example

2021-02-23 17:48 UTC, nathanstitt approved these changes

2021-02-23 17:49 UTC, nathanstitt commented
looks good, but specs failed though :(

2021-02-23 18:07 UTC, Dantemss commented on app/controllers/api/v1/users_controller.rb
> +                     is_teacher: current_human_user.roles.any?(&:teacher?)
This will be false before they create their first course, making the offerings not be returned. Will that work?

2021-02-23 18:09 UTC, nathanstitt requested changes

2021-02-23 18:09 UTC, nathanstitt commented on app/controllers/api/v1/users_controller.rb
> +                     is_teacher: current_human_user.roles.any?(&:teacher?)
good catch @Dantemss - yes we'll need the offerings to allow teachers to create their first course.

Josiah, I think you can use the same logic that the existing offering access policy uses:
https://github.com/openstax/tutor-server/blob/main/app/access_policies/offering_access_policy.rb#L5

2021-02-23 18:55 UTC, jivey commented on app/controllers/api/v1/users_controller.rb
> +                     is_teacher: current_human_user.roles.any?(&:teacher?)
Yes good call, fixed

2021-02-24 17:08 UTC, nathanstitt approved these changes
The homework_assistant spec's still flaky. we can merge and make a followup for that though

2021-02-24 17:12 UTC, merged