generate payment codes for students
openstax/tutor-server pull request #2333
Opened 2021-06-25 23:20 UTC by jivey

2021-06-28 21:31 UTC, nathanstitt requested changes

2021-06-28 21:31 UTC, nathanstitt commented on app/models/payment_code.rb
> +  end
this method makes me nervous.  A code should never change, because once we hand them out we MUST honor them.  It'd suck if a student somehow paid for a code that we'd overwritten and no longer had a record of.  

I see the code column has a unique index, and since collisions should be very unlikely, how about adding a try/catch block in the generate codes routine and just loop through again if it does happen

2021-06-28 21:32 UTC, nathanstitt commented on app/models/payment_code.rb
> +  end
I also think @Dantemss has an `immutablerecord`  class somewhere, we should use that so that codes cannot be deleted

2021-06-29 23:43 UTC, jivey commented on app/models/payment_code.rb
> +  end
@nathanstitt Thoughts if https://github.com/openstax/tutor-server/pull/2333/commits/e4a4a1570e074db74e397b89150ba9caad2c7e22 addresses those concerns? If not I'm totally good with moving this behavior into the routine 👍

2021-07-05 20:48 UTC, Dantemss requested changes
Looks good other than my comments below

2021-07-05 20:48 UTC, Dantemss commented on app/routines/generate_payment_code_report.rb
> +    path = File.join('tmp', 'exports', "payment-code-report.csv")
This has to end up in the exports S3 bucket somehow, you can look at the code on https://github.com/openstax/tutor-server/blob/c42e7bb9d3078763cfd7a530ca6e5e9905b50884/app/subsystems/tasks/models/performance_report_export.rb or roll your own using ActiveStorage because I'm not a fan of Carrierwave either.

The bucket name comes from the secrets.

2021-07-05 20:48 UTC, Dantemss commented on app/routines/generate_payment_code_report.rb
> +      PaymentCode.in_batches.each_record do |pc|
Might wanna have a parameter in this routine to limit this by dates or something, since we probably won't care about really old codes in a few years.

2021-07-05 20:48 UTC, Dantemss commented on app/models/payment_code.rb
> +  after_rollback :regenerate_code
Not entirely sure this will help with the mass generation, since if any code fails then GeneratePaymentCodes will fail. Maybe instead add something to GeneratePaymentCodes to handle failures and retry.

2021-07-05 20:48 UTC, Dantemss commented on app/routines/generate_payment_codes.rb
> +      codes << PaymentCode.create!(prefix: prefix).code
I believe create! will fail the entire routine (and report to Sentry etc) if it fails so to handle failures you'll need either:
- Use `PaymentCode.create(...)`, assign it to a variable and regenerate or just make a new one if it fails OR
- Keep using `PaymentCode.create!(...)` but rescue the error you get (probably `ActiveRecord::RecordInvalid`)

You probably want to test the failure mode, for this I think you test can do something like this:

First split `generate_code` into `generate_code` and `set_code` (which calls `generate_code`) so the return value of `generate_code` is actually used to set the record's code (make sure the before_validation calls `set_code` instead), then add this to your test:
```
allow_any_instance_of(PaymentCode).to receive(:generate_code).and_return('1', '1', '2')
```

So the first 2 will be a duplicate code and the last one will be different.

2021-07-05 21:07 UTC, jivey commented on app/routines/generate_payment_codes.rb
> +      codes << PaymentCode.create!(prefix: prefix).code
Yeah I meant to swap to just `create` here after I made the model capable of handling the collision by itself. Good notes on testing a failure state, I'll take a look.

2021-07-06 14:37 UTC, nathanstitt commented on app/models/payment_code.rb
> +  end
think that's good but how about having it throw an exception if it's persisted?  Right now it'll silently fail to set_code so whatever's calling it wouldn't know that it shouldn't be doing so

2021-07-06 15:34 UTC, nathanstitt approved these changes

2021-07-06 16:45 UTC, jivey commented on app/routines/generate_payment_code_report.rb
> +      PaymentCode.in_batches.each_record do |pc|
Switched it to default to `1.year.ago`, we can add a datepicker to the admin view at some point.

2021-07-06 18:26 UTC, merged