Salesforce sync failures admin page
openstax/tutor-server pull request #2401
Opened 2021-10-29 19:14 UTC by Dantemss

- Added an admin page listing Salesforce sync failures

2021-11-03 15:12 UTC, TomWoodward requested changes

2021-11-03 15:12 UTC, TomWoodward commented on app/controllers/admin/salesforce_controller.rb
> +              SELECT *
can we do this through the orm with like a has many through or something? why is the inline sql necessary?

2021-11-03 15:12 UTC, TomWoodward commented on app/controllers/admin/salesforce_controller.rb
> +              EXISTS (
is it really necessary to filter out courses without active students/teachers? you already have the `not_ended` filter. are there a lot of courses that are created past the preview stage and then abandoned?

if we need this we probably want to document that its happening, the help text on the page doesn't indicate this filter exists.

2021-11-05 18:27 UTC, Dantemss commented on app/controllers/admin/salesforce_controller.rb
> +              EXISTS (
I figured that we do not care about courses if the teacher never enrolled anyone and then left it, but yeah I guess we can still display them to document it.

2021-11-05 22:00 UTC, jivey approved these changes

2021-11-05 22:02 UTC, merged